export const hundreedPercent = 100;
export const relativeNumber = 100000;
export const totalPeriod = 'Total';
export const newPeriod = 'New';
export const defaultView = 'absolute values';
export const relativeView = 'relative values, per 100000';
export const percentageView = 'percentage values, %';
export const defaultInfo = 'World';
export const worldPopulation = 7827000000;
export const confirmedStatus = 'Confirmed';
export const recoveredStatus = 'Recovered';
export const deathsStatus = 'Deaths';
export const navigatePrev = '<';
export const navigateNext = '>';
export const populationUrl = 'https://restcountries.eu/rest/v2/all?fields=population;flag;alpha2Code';
export const covidSummaryUrl = 'https://api.covid19api.com/summary';
export const worldTimelineUrl = 'https://disease.sh/v3/covid-19/historical/all';
export const countryTimelineUrl = 'https://disease.sh/v3/covid-19/historical/';
export const daysInTimeline = '?lastdays=300';
